# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(778, 632)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setStyleSheet("/* Apply to the entire application */\n"
"QWidget {\n"
"    background-color: #1c1c1c; /* Dark gray background */\n"
"    color: #f0f0f0; /* Light text color */\n"
"\n"
"}\n"
"\n"
"/* Apply to labels */\n"
"QLabel {\n"
"    color: #f44336; /* Bright red text color */\n"
"    font-size: 16px; /* Adjusted font size for labels */\n"
"    padding: 5px; /* Add padding for labels */\n"
"}\n"
"\n"
"/* Apply to buttons */\n"
"QPushButton {\n"
"    background-color: #d32f2f; /* Bright red background */\n"
"    border: none; /* No border */\n"
"    color: #ffffff; /* White text color */\n"
"    padding: 10px 20px; /* Padding inside the button */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    font-size: 14px; /* Adjust font size */\n"
"    margin: 5px; /* Margin around buttons */\n"
"    transition: background-color 0.3s ease; /* Smooth transition */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #e53935; /* Slightly brighter red on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #b71c1c; /* Darker red when pressed */\n"
"}\n"
"\n"
"/* Apply to form frame */\n"
"QFrame#formFrame {\n"
"    background-color: #2e2e2e; /* Slightly lighter gray for formFrame */\n"
"    border: 2px solid #d32f2f; /* Bright red border */\n"
"    border-radius: 10px; /* Rounded corners */\n"
"    padding: 15px; /* Padding inside the frame */\n"
"    margin: 10px; /* Margin around frame */\n"
"}\n"
"\n"
"/* Apply to tab widget */\n"
"QTabWidget::pane {\n"
"    border: 1px solid #d32f2f; /* Bright red border around tab pane */\n"
"    background-color: #1c1c1c; /* Dark background for tab pane */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    padding: 10px; /* Padding inside the tab pane */\n"
"}\n"
"\n"
"\n"
"QTabBar::tab {\n"
"    background: #2e2e2e; /* Dark gray background for tabs */\n"
"    color: #f0f0f0; /* Light text color */\n"
"    border: 1px solid #d32f2f; /* Bright red border */\n"
"    border-bottom-color: #1c1c1c; /* Same as pane background to blend */\n"
"    border-radius: 5px 5px 0 0; /* Rounded top corners */\n"
"    padding: 8px 16px; /* Padding inside tabs */\n"
"    margin: 2px; /* Margin between tabs */\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background: #d32f2f; /* Bright red background for selected tab */\n"
"    color: #ffffff; /* White text color for selected tab */\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    background: #e53935; /* Slightly brighter red on hover */\n"
"}\n"
"\n"
"/* Optional: Style for QLineEdit, QComboBox, etc. */\n"
"QLineEdit, QComboBox {\n"
"    background-color: #3e3e3e; /* Dark gray background */\n"
"    border: 1px solid #d32f2f; /* Bright red border */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    color: #f0f0f0; /* Light text color */\n"
"    padding: 5px; /* Padding inside the input */\n"
"}\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(-1)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.formFrame = QtWidgets.QFrame(self.tab)
        self.formFrame.setMaximumSize(QtCore.QSize(16777215, 250))
        self.formFrame.setStyleSheet("background-color: rgba( 0, 0, 0, 75% );\n"
"    border-radius: 10px;")
        self.formFrame.setObjectName("formFrame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.formFrame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.browse_line = QtWidgets.QLineEdit(self.formFrame)
        self.browse_line.setStyleSheet("color: white;")
        self.browse_line.setObjectName("browse_line")
        self.gridLayout_2.addWidget(self.browse_line, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.formFrame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgb(255, 255, 255);\n"
"background-color: rgba( 0, 0, 0, 0% )")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.extract = QtWidgets.QPushButton(self.formFrame)
        self.extract.setStyleSheet(" background-color: white;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"color:black;")
        self.extract.setAutoDefault(False)
        self.extract.setDefault(False)
        self.extract.setFlat(False)
        self.extract.setObjectName("extract")
        self.horizontalLayout_2.addWidget(self.extract)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 2, 1, 1)
        self.browse_btn = QtWidgets.QPushButton(self.formFrame)
        self.browse_btn.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Baloo Bhaijaan")
        font.setPointSize(-1)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.browse_btn.setFont(font)
        self.browse_btn.setObjectName("browse_btn")
        self.gridLayout_2.addWidget(self.browse_btn, 0, 3, 1, 1)
        self.gridLayout_3.addWidget(self.formFrame, 4, 0, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser.setMinimumSize(QtCore.QSize(0, 250))
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_3.addWidget(self.textBrowser, 2, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.tab)
        self.progressBar.setStyleSheet("QProgressBar {\n"
"    border: 2px solid #d5d5d5;\n"
"    border-radius: 5px;\n"
"    background: #f5f5f5;\n"
"    color: rgb(0, 0, 0); /* Black font color for the percentage text */\n"
"    text-align: center; /* Center the text inside the progress bar */\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background: #ff3333; /* Red color for the progress chunk */\n"
"    width: 10px; /* Width of the progress chunk */\n"
"}\n"
"")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_3.addWidget(self.progressBar, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "ECU TEST tool"))
        self.browse_line.setText(_translate("MainWindow", "browse to select the HTML directory..."))
        self.label_2.setText(_translate("MainWindow", "input"))
        self.extract.setText(_translate("MainWindow", "EXTRACT"))
        self.browse_btn.setText(_translate("MainWindow", "Browse"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
